[package]
name = "site"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
feed-rs = "2.3.1"
maud = "0.27.0"
pulldown-cmark = "0.13.0"
regex = "1.11.2"
thiserror = "2.0.16"
toml = "0.9.7"
ureq = "3.1.4"
url = "2.5.8"
walkdir = "2.5.0"
